Conversation.create!([
  {starter_id: 2},
  {starter_id: 2},
  {starter_id: 2},
  {starter_id: 1},
  {starter_id: 1},
  {starter_id: 1}
])
Message.create!([
  {user_id: nil, body: "엄마", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "엄마아빠", translated: nil, read: nil, conversation_id: nil},
  {user_id: 1, body: "애 엄마", translated: nil, read: nil, conversation_id: nil},
  {user_id: 1, body: "엄마 where is rosa", translated: nil, read: nil, conversation_id: nil},
  {user_id: 1, body: "엄마 where is 언니", translated: nil, read: nil, conversation_id: nil},
  {user_id: 1, body: "씨러", translated: nil, read: nil, conversation_id: nil},
  {user_id: 1, body: "엄마 뭐야", translated: nil, read: nil, conversation_id: nil},
  {user_id: 1, body: "what's for 전역", translated: nil, read: nil, conversation_id: nil},
  {user_id: 1, body: "언니 어디가", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "엄마 and 아빠", translated: nil, read: nil, conversation_id: nil},
  {user_id: 1, body: "언재와", translated: nil, read: nil, conversation_id: 1},
  {user_id: 1, body: "몰리", translated: nil, read: nil, conversation_id: 1},
  {user_id: nil, body: "엄마 where are you", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "엄마 where are you", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "where is 엄마", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "왜 엄마", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "왜 아빠", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "where is 애니", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "엄마 where are you", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "where is 엄마", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "언니 call 애니", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "애니 call 언니", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "애니 call 언니", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "annie call rosa", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "annie", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "애니", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "언니", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "애니", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "언니", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "언니", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "언니", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "언니", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "언니", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "언니", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "언니", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "Mom", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "Mom", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "Mom", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "Dad", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "Dad", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "Mom", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "Mom", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "엄마", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "엄마", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "엄마", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "언니", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "엄마", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "엄마", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "아빠", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "왜", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "왜", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "왜", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "아니", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "엄마", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "엄마", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "아빠", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "언니", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "엄마", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "아빠", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "annie", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "rosa", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "언니", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "언니", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "{\"body\"=>\"엄마\"}", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "엄마", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "엄마", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "엄마", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "엄마아빠", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "엄마 and 아빠", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "엄마 and 아빠", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "엄마", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "엄마", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "아빠", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "엄마", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "아빠", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "엄마", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "아빠", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "언니", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "언니", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "언니", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "언니", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "언니", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "애니", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "언니", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "언니", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "언니", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "언니", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "애니", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "언니", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "애니", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "언니", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "애니", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "엄마", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "언니", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "애니", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "언니", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "엄마", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "아빠", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "엄마", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "엄마", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "엄마", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "아빠", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "엄마", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "엄마", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "엄마", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "엄마", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "엄마", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "엄마", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "", translated: nil, read: nil, conversation_id: nil},
  {user_id: nil, body: "엄마", translated: nil, read: nil, conversation_id: nil},
  {user_id: 1, body: "몰리", translated: nil, read: nil, conversation_id: 1},
  {user_id: 1, body: "몰리", translated: nil, read: nil, conversation_id: 1},
  {user_id: 1, body: "what's for 전역", translated: nil, read: nil, conversation_id: 1}
])
User.create!([
  {name: nil, phone_number: nil, email: "mom@gmail.com", preferred_language: nil, password_digest: "$2a$10$efF.KWOQrZzSdSEJXdp7eeXn9JD4886XYVtmY1Drn5W7Mgm25STFG"},
  {name: "dad", phone_number: nil, email: "dad@gmail.com", preferred_language: nil, password_digest: "$2a$10$.xUqN80OOvmNybRCffzGruMHOeSWrkWuxj8juDghYWJdAzzJABNym"},
  {name: "rosa", phone_number: nil, email: "rosa@gmail.com", preferred_language: nil, password_digest: "$2a$10$TkIWbQZ2zmKFQGC7/ZRjXe6hx8xsHiJb7tBcCr5DNM8pSOUjf8gzC"},
  {name: "annie", phone_number: nil, email: "annie@gmail.com", preferred_language: nil, password_digest: "$2a$10$fxBKjewWPI9id4tYYB8KnOtIaaTWyOyVGVevo8qBLqwU9CSoPa0yW"},
  {name: "Patty Hwang", phone_number: "6108642346", email: "patty@gmail.com", preferred_language: "Korean", password_digest: "$2a$10$ghiWX3/eQOeisDrDJbCy1uc63h.SvxJNxI5w3mEmqmBS5vg4YXG0m"}
])
