Conversation.create!([
  {starter_id: 1, name: "mom"},
  {starter_id: 1, name: "patty"},
  {starter_id: 1, name: "salmon"},
  {starter_id: 1, name: "dad"},
  {starter_id: 1, name: "Rosa"},
  {starter_id: 1, name: "Annie"}
])
Message.create!([
  {user_id: nil, body: "BUTTER", translated: nil, read: nil, conversation_id: 1},
  {user_id: nil, body: "GREAT", translated: nil, read: nil, conversation_id: 1},
  {user_id: nil, body: "ok", translated: nil, read: nil, conversation_id: 1},
  {user_id: nil, body: "oik", translated: nil, read: nil, conversation_id: 1},
  {user_id: nil, body: "grr", translated: nil, read: nil, conversation_id: 1},
  {user_id: nil, body: "grr", translated: nil, read: nil, conversation_id: 1},
  {user_id: nil, body: "ok", translated: nil, read: nil, conversation_id: 1},
  {user_id: nil, body: "ok", translated: nil, read: nil, conversation_id: 1},
  {user_id: nil, body: "ok", translated: nil, read: nil, conversation_id: 1},
  {user_id: nil, body: "ok", translated: nil, read: nil, conversation_id: 1},
  {user_id: nil, body: "kjh", translated: nil, read: nil, conversation_id: 1},
  {user_id: nil, body: "hi", translated: nil, read: nil, conversation_id: 1},
  {user_id: nil, body: "timber!!!", translated: nil, read: nil, conversation_id: 1},
  {user_id: nil, body: "say it loud say it proud", translated: nil, read: nil, conversation_id: 1},
  {user_id: nil, body: "응", translated: nil, read: nil, conversation_id: 4},
  {user_id: nil, body: "아랐어", translated: nil, read: nil, conversation_id: 4},
  {user_id: nil, body: "언니 and 애니", translated: nil, read: nil, conversation_id: 4},
  {user_id: nil, body: "엄마", translated: nil, read: nil, conversation_id: 110},
  {user_id: nil, body: "hi 엄마", translated: nil, read: nil, conversation_id: 110},
  {user_id: nil, body: "hi 엄마", translated: nil, read: nil, conversation_id: 110},
  {user_id: nil, body: "hi 엄마", translated: nil, read: nil, conversation_id: 110},
  {user_id: nil, body: "hi 엄마", translated: nil, read: nil, conversation_id: 110},
  {user_id: nil, body: "아빠", translated: nil, read: nil, conversation_id: 110},
  {user_id: nil, body: "아빠", translated: nil, read: nil, conversation_id: 110},
  {user_id: nil, body: "아빠", translated: nil, read: nil, conversation_id: 110},
  {user_id: nil, body: "아빠", translated: nil, read: nil, conversation_id: 110},
  {user_id: nil, body: "아랐어", translated: nil, read: nil, conversation_id: 110},
  {user_id: nil, body: "아니", translated: nil, read: nil, conversation_id: 110},
  {user_id: nil, body: "아랐어", translated: nil, read: nil, conversation_id: 110},
  {user_id: nil, body: "아니", translated: nil, read: nil, conversation_id: 110},
  {user_id: nil, body: "엄마", translated: nil, read: nil, conversation_id: 110},
  {user_id: nil, body: "아니", translated: nil, read: nil, conversation_id: 110},
  {user_id: nil, body: "아니아니아니아니", translated: nil, read: nil, conversation_id: 110},
  {user_id: nil, body: "응응응", translated: nil, read: nil, conversation_id: 110},
  {user_id: nil, body: "hi 언니", translated: nil, read: nil, conversation_id: 112},
  {user_id: nil, body: "hey 엄마", translated: nil, read: nil, conversation_id: 113},
  {user_id: nil, body: "hi 엄마", translated: nil, read: nil, conversation_id: 114},
  {user_id: nil, body: "hi 아빠", translated: nil, read: nil, conversation_id: 115},
  {user_id: nil, body: "hey 엄마", translated: nil, read: nil, conversation_id: 118},
  {user_id: nil, body: "아랐어", translated: nil, read: nil, conversation_id: 120},
  {user_id: nil, body: "아니", translated: nil, read: nil, conversation_id: 123},
  {user_id: nil, body: "yes", translated: nil, read: nil, conversation_id: 123},
  {user_id: nil, body: "아랐어", translated: nil, read: nil, conversation_id: 123},
  {user_id: nil, body: "goodbye", translated: nil, read: nil, conversation_id: 123},
  {user_id: nil, body: "아니", translated: nil, read: nil, conversation_id: 123},
  {user_id: nil, body: "응", translated: nil, read: nil, conversation_id: 123},
  {user_id: nil, body: "아니", translated: nil, read: nil, conversation_id: 121},
  {user_id: nil, body: "엄마", translated: nil, read: nil, conversation_id: 122},
  {user_id: nil, body: "아니", translated: nil, read: nil, conversation_id: 122},
  {user_id: nil, body: "hi 엄마", translated: nil, read: nil, conversation_id: 4},
  {user_id: nil, body: "hi 엄마", translated: nil, read: nil, conversation_id: 22},
  {user_id: nil, body: "hi 엄마", translated: nil, read: nil, conversation_id: 22},
  {user_id: nil, body: "아랐어 엄마", translated: nil, read: nil, conversation_id: 22},
  {user_id: nil, body: "hi 엄마", translated: nil, read: nil, conversation_id: 111},
  {user_id: nil, body: "hi 아빠", translated: nil, read: nil, conversation_id: 111},
  {user_id: nil, body: "hi 아빠", translated: nil, read: nil, conversation_id: 110},
  {user_id: nil, body: "엄마", translated: nil, read: nil, conversation_id: 110},
  {user_id: nil, body: "엄마", translated: nil, read: nil, conversation_id: 110},
  {user_id: nil, body: "hi 엄마", translated: nil, read: nil, conversation_id: 110},
  {user_id: nil, body: "아빠", translated: nil, read: nil, conversation_id: 110},
  {user_id: nil, body: "아니", translated: nil, read: nil, conversation_id: 110},
  {user_id: nil, body: "hi 엄마", translated: nil, read: nil, conversation_id: 110},
  {user_id: nil, body: "hi 엄마", translated: nil, read: nil, conversation_id: 110},
  {user_id: nil, body: "hi 엄마", translated: nil, read: nil, conversation_id: 110},
  {user_id: nil, body: "", translated: nil, read: nil, conversation_id: 111},
  {user_id: nil, body: "아니", translated: nil, read: nil, conversation_id: 116},
  {user_id: nil, body: "아빠", translated: nil, read: nil, conversation_id: 115},
  {user_id: nil, body: "아니", translated: nil, read: nil, conversation_id: 115},
  {user_id: nil, body: "아니", translated: nil, read: nil, conversation_id: 121},
  {user_id: nil, body: "hi 엄마", translated: nil, read: nil, conversation_id: 121},
  {user_id: nil, body: "buttercup hi", translated: nil, read: nil, conversation_id: 115},
  {user_id: nil, body: "아니", translated: nil, read: nil, conversation_id: 115},
  {user_id: nil, body: "oh 응", translated: nil, read: nil, conversation_id: 115},
  {user_id: nil, body: "who is doing this?", translated: nil, read: nil, conversation_id: 124},
  {user_id: nil, body: "and 왜", translated: nil, read: nil, conversation_id: 124},
  {user_id: nil, body: "when can we eat?", translated: nil, read: nil, conversation_id: 124},
  {user_id: nil, body: "엄마", translated: nil, read: nil, conversation_id: 124},
  {user_id: nil, body: "BUTTER", translated: nil, read: nil, conversation_id: 1},
  {user_id: nil, body: "BUTTER", translated: nil, read: nil, conversation_id: 1},
  {user_id: nil, body: "BUTTER", translated: nil, read: nil, conversation_id: 1}
])
User.create!([
  {name: nil, phone_number: nil, email: "mom@gmail.com", preferred_language: nil, password_digest: "$2a$10$efF.KWOQrZzSdSEJXdp7eeXn9JD4886XYVtmY1Drn5W7Mgm25STFG"},
  {name: "dad", phone_number: nil, email: "dad@gmail.com", preferred_language: nil, password_digest: "$2a$10$.xUqN80OOvmNybRCffzGruMHOeSWrkWuxj8juDghYWJdAzzJABNym"},
  {name: "rosa", phone_number: nil, email: "rosa@gmail.com", preferred_language: nil, password_digest: "$2a$10$TkIWbQZ2zmKFQGC7/ZRjXe6hx8xsHiJb7tBcCr5DNM8pSOUjf8gzC"},
  {name: "annie", phone_number: nil, email: "annie@gmail.com", preferred_language: nil, password_digest: "$2a$10$fxBKjewWPI9id4tYYB8KnOtIaaTWyOyVGVevo8qBLqwU9CSoPa0yW"},
  {name: "Patty Hwang", phone_number: "6108642346", email: "patty@gmail.com", preferred_language: "Korean", password_digest: "$2a$10$od0BK06bXFqoW2DnI3y/HuzilnvR3Pj1bBOE9p9Opv.4i/j3KLAfm"}
])
